spring.application.name=weightGraph

#DataSource
#Postgresドライバーの設定
spring.datasource.driver-class-name=org.postgresql.Driver
#データベースへの接続URL
spring.datasource.url=jdbc:postgresql://localhost:5432/springdb
#ユーザー名
spring.datasource.username=springuser
#パスワード
spring.datasource.password=p@ss
#スクリプト初期化モード
spring.sql.init.mode=always
#Log
logging.level.com.example.webapp.repository=DEBUG